GET https://anticona23-potential-halibut-jxpjr7vj9qv2pj59-8080.preview.app.github.dev
###
@server = https://anticona23-potential-halibut-jxpjr7vj9qv2pj59-8080.preview.app.github.dev
###
GET {{server}}

### Listando todo
GET {{server}}/cursos

### Agreagndo
POST {{server}}/cursos
Content-Type: application/json

{"nombre": "Servicios Web 1", "credito": 3}

### Listando por codigo
GET {{server}}/cursos/5

### Editando
PATCH {{server}}/cursos/5
Content-Type: application/json

{"creditos": "4"}

###
GET {{server}}/cursos?size=3&page=0

###
GET {{server}}/cursos?size=1&page=0&sort=creditos.desc

###
GET {{server}}/cursos?size=1&page=1&sort=creditos.desc

###
GET {{server}}/cursos/search/findByNombre?nombre=Matematica
